var nome = 'Gui';
var idade = 10;
var isTryber = true;
var stringOrNumber = 'gui';
stringOrNumber = 'Guigo';
var anyValue = 10;
anyValue = 'GUigo';
anyValue = true;
anyValue = undefined;
var x;
var y = 0;
var z = 123.456;
var studentStatus;
(function (studentStatus) {
    studentStatus[studentStatus["Active"] = 1] = "Active";
    studentStatus[studentStatus["Inactive"] = 2] = "Inactive";
    studentStatus[studentStatus["Paused"] = 3] = "Paused";
})(studentStatus || (studentStatus = {}));
var newStudentStatus = studentStatus.Active;
var StatusCodes;
(function (StatusCodes) {
    StatusCodes[StatusCodes["OK"] = 200] = "OK";
    StatusCodes[StatusCodes["BadRequest"] = 400] = "BadRequest";
    StatusCodes[StatusCodes["Unauthorized"] = 401] = "Unauthorized";
    StatusCodes[StatusCodes["PaymentRequired"] = 402] = "PaymentRequired";
    StatusCodes[StatusCodes["Forbidden"] = 403] = "Forbidden";
    StatusCodes[StatusCodes["NotFound"] = 404] = "NotFound";
})(StatusCodes || (StatusCodes = {}));
var ok = StatusCodes.OK;
var okIndex = StatusCodes["OK"];
var stringBadRequest = StatusCodes[400];
// console.log(ok);
// console.log(okIndex);
// console.log(stringBadRequest);
var DaysOfWeek;
(function (DaysOfWeek) {
    DaysOfWeek[DaysOfWeek["SUNDAY"] = 1] = "SUNDAY";
    DaysOfWeek[DaysOfWeek["MONDAY"] = 2] = "MONDAY";
    DaysOfWeek[DaysOfWeek["TUESDAY"] = 3] = "TUESDAY";
    DaysOfWeek[DaysOfWeek["WEDNESDAY"] = 4] = "WEDNESDAY";
    DaysOfWeek[DaysOfWeek["THURSDAY"] = 5] = "THURSDAY";
    DaysOfWeek[DaysOfWeek["FRIDAY"] = 6] = "FRIDAY";
    DaysOfWeek[DaysOfWeek["SATURDAY"] = 7] = "SATURDAY";
})(DaysOfWeek || (DaysOfWeek = {}));
var today = DaysOfWeek[2];
var todaysIndex = DaysOfWeek.MONDAY;
var yesterday = DaysOfWeek[7];
console.log('weekDay', today);
console.log('weekDay', todaysIndex);
console.log('weekDay', yesterday);
var ColorsOfTheRainbow;
(function (ColorsOfTheRainbow) {
    ColorsOfTheRainbow[ColorsOfTheRainbow["red"] = 1] = "red";
    ColorsOfTheRainbow[ColorsOfTheRainbow["orange"] = 2] = "orange";
    ColorsOfTheRainbow[ColorsOfTheRainbow["yellow"] = 3] = "yellow";
    ColorsOfTheRainbow[ColorsOfTheRainbow["green"] = 4] = "green";
    ColorsOfTheRainbow[ColorsOfTheRainbow["blue"] = 5] = "blue";
    ColorsOfTheRainbow[ColorsOfTheRainbow["indigo"] = 6] = "indigo";
    ColorsOfTheRainbow[ColorsOfTheRainbow["violet"] = 7] = "violet";
})(ColorsOfTheRainbow || (ColorsOfTheRainbow = {}));
console.log('color', ColorsOfTheRainbow[3]);
var PrinterActions;
(function (PrinterActions) {
    PrinterActions[PrinterActions["salvar"] = 1] = "salvar";
    PrinterActions[PrinterActions["imprimir"] = 2] = "imprimir";
    PrinterActions[PrinterActions["abrir"] = 3] = "abrir";
    PrinterActions[PrinterActions["visualizar"] = 4] = "visualizar";
    PrinterActions[PrinterActions["fechar"] = 5] = "fechar";
})(PrinterActions || (PrinterActions = {}));
console.log('printerActions', PrinterActions[4]);
var CardinalPoints;
(function (CardinalPoints) {
    CardinalPoints[CardinalPoints["north"] = 1] = "north";
    CardinalPoints[CardinalPoints["east"] = 2] = "east";
    CardinalPoints[CardinalPoints["south"] = 3] = "south";
    CardinalPoints[CardinalPoints["west"] = 4] = "west";
})(CardinalPoints || (CardinalPoints = {}));
console.log('Cardinals', CardinalPoints[2]);
